name = "websocket-server"
main = "./src/cf-worker/index.ts"
compatibility_date = "2025-06-08"
# compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "WEBSOCKET_SERVER"
class_name = "WebSocketServer"

[[migrations]]
tag = "v1"
new_classes = ["WebSocketServer"]

[[d1_databases]]
binding = "DB"
database_name = "livestore-sync"
database_id = "d8e7001d-2058-448c-9025-ce16df6b31a9"
