name = "websocket-server"
account_id = "548a6ac51a0761a09335ec5ee95fcfaf"
workers_dev = true
main = "./src/cf-worker/index.ts"
compatibility_date = "2025-06-08"

[[durable_objects.bindings]]
name = "WEBSOCKET_SERVER"
class_name = "WebSocketServer"

[[migrations]]
tag = "v1"                        
new_sqlite_classes = ["WebSocketServer"]

[[d1_databases]]
binding = "DB"
database_name = "livestore-sync"
database_id = "d8e7001d-2058-448c-9025-ce16df6b31a9"
